use ExamenGabrielPazosAlonso;

INSERT INTO Peliculas (Titulo, Director, Sinopsis) VALUES
('Room', 'Lenny Abrahamson', 'Para Jack, un niño de cinco años, la habitación es el mundo entero, el lugar donde nació, donde come, juega y aprende con su madre. Por la noche, mamá lo pone a dormir en el armario, por si viene el viejo Nick. La habitación es el hogar de Jack, mientras que para su madre es el cubículo donde lleva siete años encerrada, secuestrada desde los diecinueve años. Con gran tesón e ingenio, la joven ha creado en ese reducido espacio una vida para su hijo, y su amor por él es lo único que le permite soportar lo insoportable. Sin embargo, la curiosidad de Jack va en aumento, a la par que la desesperación de su madre, que sabe que la habitación no podrá contener ambas cosas por mucho más tiempo.'),
('La corona partida', 'Jordi Frades', 'Narrará lo ocurrido tras la muerte de Isabel la Católica y los tiempos de incertidumbre que se vivieron por la lucha de poder entre Fernando el Católico y Felipe el Hermoso cuya principal víctima fue Juana la Loca, legítima heredera. '),
('La ley del mercado','Stéphane Brizé','Después de 20 meses en el paro, Thierry, un hombre de 51 años, encuentra un nuevo trabajo, pero pronto tendrá que enfrentarse a un dilema moral: ¿puede aceptar cualquier cosa con tal de conservar su trabajo? '),
('Nahid','Ida Panahandeh','Nahid es una joven divorciada que vive sola con su hijo de diez años en una ciudad del norte de Irán junto al Mar Caspio. Conforme a las normas que rigen la sociedad iraní, la custodia de un hijo le corresponde al padre, aunque en este caso su exmarido se la ha cedido a condición de que no se vuelva a casar. La relación entre Nahid y otro hombre que la ama apasionadamente y desea casarse con ella complicará su situación como mujer y como madre.'),
('Carol','Todd Haynes','Nueva York, años 50. Therese Belivet (Rooney Mara), una joven dependienta de una tienda de Manhattan que sueña con una vida mejor, conoce un día a Carol Aird (Cate Blanchett), una mujer elegante y sofisticada que se encuentra atrapada en un matrimonio infeliz. Entre ellas surge una atracción inmediata, cada vez más intensa y profunda, que cambiará sus vidas para siempre. '),
('The Revenant)','Alejandro González Iñárritu','Año 1823. En las profundidades de la América salvaje, el explorador Hugh Glass (Leonardo DiCaprio) participa junto a su hijo mestizo Hawk en una expedición de tramperos que recolecta pieles. Glass resulta gravemente herido por el ataque de un oso y es abandonado a su suerte por un traicionero miembro de su equipo, John Fitzgerald (Tom Hardy). Con la fuerza de voluntad como su única arma, Glass deberá enfrentarse a un territorio hostil, a un invierno brutal y a la guerra constante entre las tribus de nativos americanos, en una búsqueda implacable para conseguir vengarse.'),
('Spotlight','Thomas McCarthy','En 2002, un equipo de reporteros de investigación del Boston Globe destapó los escándalos de pederastia cometidos durante décadas por curas de Massachussets. La publicación de estos hechos, que la archidiócesis de Boston intentó ocultar, sacudió a la Iglesia Católica como institución.'),
('Creed. La leyenda de Rocky','Ryan Coogler','Adonis Johnson no llegó a conocer a su padre, el campeón del mundo de los pesos pesados Apollo Creed, que falleció antes de que él naciera. Sin embargo, nadie puede negar que lleva el boxeo en la sangre, por lo que pone rumbo a Filadelfia, el lugar en el que se celebró el legendario combate entre su padre y Rocky Balboa. Una vez allí, Adonis busca a Rocky y le pide que sea su entrenador. A pesar de que este insiste en que ya ha dejado ese mundo para siempre, Rocky ve en Adonis la fuerza y determinación que tenía su enconado rival, y que terminó por convertirse en su mejor amigo. Finalmente, acepta entrenarle a pesar de estar librando su propio combate contra un rival más letal que cualquiera a los que se enfrentó en el cuadrilátero.'),
('La gran apuesta','Adam McKay','Cuando cuatro tipos fuera del sistema descubren que los grandes bancos, los medios de comunicación y el gobierno se niegan a reconocer el colapso de la economía, tienen una idea: "La Gran Apuesta"… pero sus inversiones de riesgo les conducen al lado oscuro de la banca moderna, donde deben poner en duda todo y a todos... Adaptación del libro “La gran apuesta” de Michael Lewis, que reflexiona sobre la quiebra del sector inmobiliario norteamericano que originó la crisis económica mundial en 2008.'),
('El gran día','Pascal Plisson','Narra la historia real de Nidhi (15 años, India), Deegii (11 años, Mongolia), Tom (19 años, Uganda) y Albert (11 años, Cuba), dos chicas y dos chicos procedentes de diferentes puntos del mundo que se enfrentan a una prueba que podrá cambiar y mejorar sus vidas para siempre. “El gran día” está cerca y los cuatro héroes llevan meses, incluso años, preparándose para afrontar este desafío. Después de tanto esfuerzo, saben que llega el momento de hacer realidad un sueño que no sólo marcará su destino, sino también el de sus familias. Es su pasión, y ahora más que nunca se centran en un sólo objetivo: el éxito.'),
('La juventud','Paolo Sorrentino','Fred Ballinger (Michael Caine), un gran director de orquesta, pasa unas vacaciones en un hotel de los Alpes con su hija Lena y su amigo Mick, un director de cine al que le cuesta acabar su última película. Fred hace tiempo que ha renunciado a su carrera musical, pero hay alguien que quiere que vuelva a trabajar; desde Londres llega un emisario de la reina Isabel, que debe convencerlo para dirigir un concierto en el Palacio de Buckingham, con motivo del cumpleaños del príncipe Felipe.'),
('Mia madre','Nanni Moretti','Margherita (Margherita Buy), una directora de cine políticamente comprometida, está a punto de separarse de Vittorio, un actor con el que tiene una hija adolescente. Su hermano (Nanni Moretti) decide dejar el trabajo para dedicarse a cuidar a su madre, gravemente enferma en el hospital. La enfermedad de la mamma y el proceso de asimilación de su inevitable pérdida alterará completamente la vida cotidiana y emocional de sus hijos.'),
('Los odiosos ocho','Quentin Tarantino','Pocos años después de la Guerra de Secesión, una diligencia avanza por el invernal paisaje de Wyoming. Los pasajeros, el cazarrecompensas John Ruth (Kurt Russell) y su fugitiva Daisy Domergue (Jennifer Jason Leigh), intentan llegar al pueblo de Red Rock, donde Ruth entregará a Domergue a la justicia. Por el camino, se encuentran con dos desconocidos: el mayor Marquis Warren (Samuel L. Jackson), un antiguo soldado de la Unión convertido en cazarrecompensas de mala reputación, y Chris Mannix (Walton Goggins), un renegado sureño que afirma ser el nuevo sheriff del pueblo. Como se aproxima una ventisca, los cuatro se refugian en la Mercería de Minnie, una parada para diligencias de un puerto de montaña. Cuando llegan al local se topan con cuatro rostros desconocidos: el mexicano Bob (Demian Bichir), Oswaldo Mobray (Tim Roth), verdugo de Red Rock, el vaquero Joe Gage (Michael Madsen) y el general confederado Sanford Smithers (Bruce Dern). Mientras la tormenta cae sobre la parada de montaña, los ocho viajeros descubren que tal vez no lleguen hasta Red Rock después de todo. '),
('La chica danesa','Tom Hooper','Drama basado en la verdadera historia de una pareja de artistas daneses, Einar y Gerda Wegener. La vida de este matrimonio dio un giro cuando Einar sustituyó a la modelo femenina que su mujer, Gerda, tenía que pintar. Cuando los retratos resultan ser un éxito, ella anima a su marido a adoptar una apariencia femenina. Lo que comenzó como un juego llevó a Einar a una metamorfosis inesperada. '),
('El hijo de Saúl','László Nemes','En el año 1944, durante el horror del campo de concentración de Auschwitz, un prisionero judío húngaro llamado Saul, miembro de los Sonderkommando -encargados de quemar los cadáveres de los prisioneros gaseados nada más llegar al campo y limpiar las cámaras de gas-, encuentra cierta supervivencia moral tratando de salvar de los hornos crematorios el cuerpo de un niño que toma como su hijo.'),
('Sufragistas','Sarah Gavron','El movimiento sufragista nació en Inglaterra en vísperas de la Primera Guerra Mundial (1914-1918). La mayoría de las sufragistas no procedían de las clases altas, sino que eran obreras que veían impotentes cómo sus pacíficas protestas no servían para nada. Entonces se radicalizaron y, en su incansable lucha por conseguir la igualdad, se arriesgaron a perderlo todo: su trabajo, su casa, sus hijos y su vida. La protagonista es Maud (Carey Mulligan), una mujer que reivindicó denodadamente la dignidad de las mujeres. '),
('La novia','Paula Ortiz','Adaptación de "Bodas de sangre", de Lorca. Desde pequeños, Leonardo, el novio y la novia han formado un triángulo inseparable, pero cuando se acerca la fecha de la boda las cosas se complican porque entre ella y Leonardo siempre ha habido algo más que amistad. La creciente tensión entre ambos es como un hilo invisible que no se puede explicar, pero tampoco romper.'),
('El puente de los espías','Steven Spielberg','James Donovan (Tom Hanks), un abogado de Brooklyn (Nueva York) se ve inesperadamente involucrado en la Guerra Fría entre su país y la URSS cuando la mismísima CIA le encarga una difícil misión: negociar la liberación de un piloto estadounidense (Austin Stowell) capturado por la Unión Soviética.'),
('Ciudadano Kane','Orson Welles','Un importante magnate estadounidense, Charles Foster Kane, dueño de una importante cadena de periódicos, de una red de emisoras, de dos sindicatos y de una inimaginable colección de obras de arte, muere en Xanadú, su fabuloso castillo de estilo oriental. La última palabra que pronuncia antes de expirar, ”Rosebud”, cuyo significado es un enigma, despierta una enorme curiosidad tanto en la prensa como entre la población. Así las cosas, un grupo de periodistas emprende una investigación para desentrañar el misterio.'),
('Todos los hombres del presidente','Alan J. Pakula','En 1972, dos jóvenes periodistas del diario The Washington Post, Bob Woodward (Robert Redford) y Carl Bernstein (Dustin Hoffman), comienzan a investigar lo que parece ser un simple allanamiento del cuartel general del Partido Demócrata en Washington. Sus descubrimientos desencadenan el llamado -caso Watergate-, que provocó la dimisión del presidente Richard Nixon'),
('Los perros de la guerra', 'John Irvin', 'Zangaro, un pequeño país de África Occidental, está dirigido desde hace años con mano de hierro por el dictador Kimba. En el otro lado del gran charco, una gran corporación de multinacionales norteamericanas lo ha puesto como objetivo para invertir varios cientos de millones de dólares. Pero antes quieren saberlo todo acerca de la estabilidad del régimen. Para ello envían a Jamie Shannon, un veterano de guerra que se hace pasar por fotógrafo de una revista de naturaleza. Los problemas no tardarán en aparecer.'),
('5 días de guerra','Renny Harlin','Un corresponsal de guerra norteamericano, el cámara que le acompaña y un nativo georgiano se ven envueltos en el fuego cruzado durante el conflicto bélico entre Rusia y Georgia. '),
('El abrazo de la serpiente','Ciro Guerra','Karamakate fue en su día un poderoso chamán del Amazonas, es el último superviviente de su pueblo, y ahora vive en aislamiento voluntario en lo más profundo de la selva. Lleva años de total soledad que lo han convertido en chullachaqui, una cáscara vacía de hombre, privado de emociones y recuerdos. Pero su vida vacía da un vuelco el día en que a su remota guarida llega Evan, un etnobotánico americano en busca de la yakruna, una poderosa planta oculta, capaz de enseñar a soñar. Karamakate accede a acompañar a Evan en su búsqueda y juntos emprenden un viaje al corazón de la selva en el que el pasado, presente y futuro se confunden, y en el que el chamán irá recuperando sus recuerdos perdidos. Esos recuerdos traen consigo vestigios de una amistad traicionada y de un profundo dolor que no liberará a Karamakate hasta que no transmita por última vez su conocimiento ancestral, el cual parecía destinado a perderse para siempre.'),
('Los viajes del viento','Ciro Guerra','1968. Ignacio Carrillo, un juglar que durante años recorrió pueblos y regiones llevando cantos con su acordeón, toma la decisión de hacer un último viaje, a través de toda la región norte de Colombia, para devolverle el instrumento a su anciano maestro, y así nunca más volver a tocar. Junto a un joven, Fermín, emprende un recorrido por la enorme diversidad de la cultura caribeña, viviendo todo tipo de aventuras y encuentros. Seleccionada por Colombia como candidata al Oscar 2010 en la categoría de película de habla no inglesa.');

INSERT INTO Peliculas (Titulo, Director, Sinopsis) VALUES
('Los perros de la guerra', 'John Irvin', 'Zangaro, un pequeño país de África Occidental, está dirigido desde hace años con mano de hierro por el dictador Kimba. En el otro lado del gran charco, una gran corporación de multinacionales norteamericanas lo ha puesto como objetivo para invertir varios cientos de millones de dólares. Pero antes quieren saberlo todo acerca de la estabilidad del régimen. Para ello envían a Jamie Shannon, un veterano de guerra que se hace pasar por fotógrafo de una revista de naturaleza. Los problemas no tardarán en aparecer.'),
('5 días de guerra','Renny Harlin','Un corresponsal de guerra norteamericano, el cámara que le acompaña y un nativo georgiano se ven envueltos en el fuego cruzado durante el conflicto bélico entre Rusia y Georgia. '),
('El abrazo de la serpiente','Ciro Guerra','Karamakate fue en su día un poderoso chamán del Amazonas, es el último superviviente de su pueblo, y ahora vive en aislamiento voluntario en lo más profundo de la selva. Lleva años de total soledad que lo han convertido en chullachaqui, una cáscara vacía de hombre, privado de emociones y recuerdos. Pero su vida vacía da un vuelco el día en que a su remota guarida llega Evan, un etnobotánico americano en busca de la yakruna, una poderosa planta oculta, capaz de enseñar a soñar. Karamakate accede a acompañar a Evan en su búsqueda y juntos emprenden un viaje al corazón de la selva en el que el pasado, presente y futuro se confunden, y en el que el chamán irá recuperando sus recuerdos perdidos. Esos recuerdos traen consigo vestigios de una amistad traicionada y de un profundo dolor que no liberará a Karamakate hasta que no transmita por última vez su conocimiento ancestral, el cual parecía destinado a perderse para siempre.'),
('Los viajes del viento','Ciro Guerra','1968. Ignacio Carrillo, un juglar que durante años recorrió pueblos y regiones llevando cantos con su acordeón, toma la decisión de hacer un último viaje, a través de toda la región norte de Colombia, para devolverle el instrumento a su anciano maestro, y así nunca más volver a tocar. Junto a un joven, Fermín, emprende un recorrido por la enorme diversidad de la cultura caribeña, viviendo todo tipo de aventuras y encuentros. Seleccionada por Colombia como candidata al Oscar 2010 en la categoría de película de habla no inglesa.');